ALTER TABLE inventory ADD COLUMN medal_honor INT NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_wins INT NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_entries INT NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_kills INT NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_deaths INT NOT NULL DEFAULT 0;
