ALTER TABLE inventory ADD COLUMN medal_honor INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_wins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_entries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_kills INTEGER NOT NULL DEFAULT 0;
ALTER TABLE inventory ADD COLUMN medal_deaths INTEGER NOT NULL DEFAULT 0;
